In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as snippets

In [ ]:
import seaborn as sns

In [ ]:
import pandas as pd
school_data = pd.read_csv('https://raw.githubusercontent.com/CunyLaguardiaDataAnalytics/datasets/master/2014-15_To_2016-17_School-_Level_NYC_Regents_Report_For_All_Variables.csv')

In [ ]:
school_data.head(20)

,School DBN,School Name,School Level,Regents Exam,Year,Total Tested,Mean Score,Number Scoring Below 65,Percent Scoring Below 65,Number Scoring 65 or Above,Percent Scoring 65 or Above,Number Scoring 80 or Above,Percent Scoring 80 or Above,Number Scoring CR,Percent Scoring CR
0,01M034,P.S. 034 Franklin D. Roosevelt,K-8,Common Core Algebra,2017,4,s,s,s,s,s,s,s,na,na
1,01M034,P.S. 034 Franklin D. Roosevelt,K-8,Living Environment,2015,16,77.9,1,6.3,15,93.8,7,43.8,na,na
2,01M034,P.S. 034 Franklin D. Roosevelt,K-8,Living Environment,2016,9,74,1,11.1,8,88.9,2,22.2,na,na
3,01M140,P.S. 140 Nathan Straus,K-8,Common Core Algebra,2016,3,s,s,s,s,s,s,s,na,na
4,01M140,P.S. 140 Nathan Straus,K-8,Common Core Algebra,2017,2,s,s,s,s,s,s,s,na,na
5,01M140,P.S. 140 Nathan Straus,K-8,Living Environment,2015,9,67.4,3,33.3,6,66.7,0,0,na,na
6,01M140,P.S. 140 Nathan Straus,K-8,Living Environment,2016,15,72.6,2,13.3,13,86.7,5,33.3,na,na
7,01M140,P.S. 140 Nathan Straus,K-8,Living Environment,2017,9,64.4,5,55.6,4,44.4,1,11.1,na,na
8,01M184,P.S. 184m Shuang Wen,K-8,Common Core Algebra,2015,49,78.4,1,2,48,98,23,46.9,48,98
9,01M184,P.S. 184m Shuang Wen,K-8,Common Core Algebra,2016,51,79,9,17.6,42,82.4,33,64.7,40,78.4
10,01M184,P.S. 184m Shuang Wen,K-8,Common Core Algebra,2017,51,84.8,0,0,51,100,44,86.3,50,98
11,01M184,P.S. 184m Shuang Wen,K-8,Living Environment,2017,55,83.9,1,1.8,54,98.2,43,78.2,na,na
12,01M188,P.S. 188 The Island School,K-8,Common Core Algebra,2015,23,62.9,14,60.9,9,39.1,0,0,2,8.7
13,01M188,P.S. 188 The Island School,K-8,Common Core Algebra,2016,22,69,6,27.3,16,72.7,2,9.1,15,68.2
14,01M188,P.S. 188 The Island School,K-8,Common Core Algebra,2017,20,67.4,7,35,13,65,1,5,10,50
15,01M188,P.S. 188 The Island School,K-8,Common Core English,2016,1,s,s,s,s,s,s,s,na,na
16,01M188,P.S. 188 The Island School,K-8,Living Environment,2016,17,62.1,9,52.9,8,47.1,0,0,na,na
17,01M188,P.S. 188 The Island School,K-8,Living Environment,2017,3,s,s,s,s,s,s,s,na,na
18,01M292,Orchard Collegiate Academy,High school,Algebra2/Trigonometry,2015,5,s,s,s,s,s,s,s,na,na
19,01M292,Orchard Collegiate Academy,High school,Algebra2/Trigonometry,2016,5,s,s,s,s,s,s,s,na,na

In [ ]:
school_data.describe()

                Year   Total Tested
count  212331.000000  212331.000000
mean     2015.956069      49.364200
std         0.799726      93.023576
min      2015.000000       1.000000
25%      2015.000000       5.000000
50%      2016.000000      20.000000
75%      2017.000000      57.000000
max      2017.000000    1729.000000

In [ ]:
school_data.shape

(212331, 15)

In [ ]:
school_data.columns

Index(['School DBN', 'School Name', 'School Level', 'Regents Exam', 'Year',
       'Total Tested', 'Mean Score', 'Number Scoring Below 65',
       'Percent Scoring Below 65', 'Number Scoring 65 or Above',
       'Percent Scoring 65 or Above', 'Number Scoring 80 or Above',
       'Percent Scoring 80 or Above', 'Number Scoring CR',
       'Percent Scoring CR'],
      dtype='object')

In [ ]:
school_data['Number Scoring CR']

0         na
1         na
2         na
3         na
4         na
          ..
212326    na
212327    na
212328    na
212329    na
212330    na
Name: Number Scoring CR, Length: 212331, dtype: object

In [ ]:
data = {'Column1': [10, 20, 30, 40, 50],
        'Column2': [10, 25, 30, 45, 50]}
df = pd.DataFrame(data)